version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitProject
  gitServerName: testGit123
  gitUrl: https://github.com/PoojaAnandGit/TestGitProject
  gitUsername: PoojaAnandGit
  gitBranch: main
